# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "movie_items", :force => true do |t|
    t.column "movie_id",  :integer
    t.column "user_id",   :integer
    t.column "upc",       :integer
    t.column "asin",      :string
    t.column "available", :boolean
  end

  create_table "movies", :force => true do |t|
    t.column "upc",                     :string, :limit => 32
    t.column "asin",                    :string, :limit => 32
    t.column "title",                   :string
    t.column "directors",               :string
    t.column "mpaa_rating",             :string
    t.column "theatrical_release_date", :date
    t.column "image_url_small",         :string
    t.column "image_url_medium",        :string
    t.column "image_url_large",         :string
    t.column "description",             :text
    t.column "actors",                  :text
  end

  create_table "requests", :force => true do |t|
    t.column "movie_item_id", :integer
    t.column "user_id",       :integer
    t.column "checked_out",   :datetime
    t.column "due_date",      :datetime
    t.column "complete",      :boolean
  end

  create_table "users", :force => true do |t|
    t.column "email",            :string
    t.column "hashed_password",  :string
    t.column "salt",             :string
    t.column "verification_key", :string
    t.column "first_name",       :string
    t.column "last_name",        :string
    t.column "dorm",             :string
    t.column "im_addr",          :string
    t.column "about",            :text
  end

end
